formatter: "markdown"

version: "0.19.0"

header-from: "_header.md"
footer-from: ""

recursive:
  enabled: false
  path: modules
  include-main: true

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}

  {{ .Requirements }}

  {{ .Providers }}

  # Examples

  ```hcl
  # example variables.tf
  {{ include "examples/default-name/variables.tf" }}
  
  # example main.tf
  {{ include "examples/default-name/main.tf" }}
  ```

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}


output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true

