formatter: "markdown"

version: "0.19.0"

header-from: "_header.md"
footer-from: ""

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}
  {{ .Requirements }}
  {{ .Providers }}
  # Examples
  ```hcl
  {{ include "examples/variables.tf" }}
  {{ include "examples/main.tf" }}
  ```
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}

output:
file: README.md
mode: replace
template: |-
  <!-- BEGIN_TF_DOCS -->
  {{.Content}} 
  <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

recursive:
  enabled: true

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true

